require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReimbursablesController do

  # This should return the minimal set of attributes required to create a valid
  # Reimbursable. As you add validations to Reimbursable, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all reimbursables as @reimbursables" do
      reimbursable = Reimbursable.create! valid_attributes
      get :index
      assigns(:reimbursables).should eq([reimbursable])
    end
  end

  describe "GET show" do
    it "assigns the requested reimbursable as @reimbursable" do
      reimbursable = Reimbursable.create! valid_attributes
      get :show, :id => reimbursable.id.to_s
      assigns(:reimbursable).should eq(reimbursable)
    end
  end

  describe "GET new" do
    it "assigns a new reimbursable as @reimbursable" do
      get :new
      assigns(:reimbursable).should be_a_new(Reimbursable)
    end
  end

  describe "GET edit" do
    it "assigns the requested reimbursable as @reimbursable" do
      reimbursable = Reimbursable.create! valid_attributes
      get :edit, :id => reimbursable.id.to_s
      assigns(:reimbursable).should eq(reimbursable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reimbursable" do
        expect {
          post :create, :reimbursable => valid_attributes
        }.to change(Reimbursable, :count).by(1)
      end

      it "assigns a newly created reimbursable as @reimbursable" do
        post :create, :reimbursable => valid_attributes
        assigns(:reimbursable).should be_a(Reimbursable)
        assigns(:reimbursable).should be_persisted
      end

      it "redirects to the created reimbursable" do
        post :create, :reimbursable => valid_attributes
        response.should redirect_to(Reimbursable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reimbursable as @reimbursable" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reimbursable.any_instance.stub(:save).and_return(false)
        post :create, :reimbursable => {}
        assigns(:reimbursable).should be_a_new(Reimbursable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reimbursable.any_instance.stub(:save).and_return(false)
        post :create, :reimbursable => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reimbursable" do
        reimbursable = Reimbursable.create! valid_attributes
        # Assuming there are no other reimbursables in the database, this
        # specifies that the Reimbursable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reimbursable.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => reimbursable.id, :reimbursable => {'these' => 'params'}
      end

      it "assigns the requested reimbursable as @reimbursable" do
        reimbursable = Reimbursable.create! valid_attributes
        put :update, :id => reimbursable.id, :reimbursable => valid_attributes
        assigns(:reimbursable).should eq(reimbursable)
      end

      it "redirects to the reimbursable" do
        reimbursable = Reimbursable.create! valid_attributes
        put :update, :id => reimbursable.id, :reimbursable => valid_attributes
        response.should redirect_to(reimbursable)
      end
    end

    describe "with invalid params" do
      it "assigns the reimbursable as @reimbursable" do
        reimbursable = Reimbursable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reimbursable.any_instance.stub(:save).and_return(false)
        put :update, :id => reimbursable.id.to_s, :reimbursable => {}
        assigns(:reimbursable).should eq(reimbursable)
      end

      it "re-renders the 'edit' template" do
        reimbursable = Reimbursable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reimbursable.any_instance.stub(:save).and_return(false)
        put :update, :id => reimbursable.id.to_s, :reimbursable => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reimbursable" do
      reimbursable = Reimbursable.create! valid_attributes
      expect {
        delete :destroy, :id => reimbursable.id.to_s
      }.to change(Reimbursable, :count).by(-1)
    end

    it "redirects to the reimbursables list" do
      reimbursable = Reimbursable.create! valid_attributes
      delete :destroy, :id => reimbursable.id.to_s
      response.should redirect_to(reimbursables_url)
    end
  end

end
